# Configuración del sitio
title: Mi Portafolio de Data Science
description: Bienvenido a mi portafolio de Data Science. Aquí encontrarás información sobre mis proyectos, habilidades y experiencia en el campo de la ciencia de datos.
url: https://reewos.github.io     # URL de tu sitio
baseurl: ""                           # Ruta base del sitio (dejar en blanco para GitHub Pages)

# Configuración de GitHub Pages
minimal_mistakes_skin: default
search: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
markdown: kramdown

timezone: PE
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikiped

plugins:
  - jekyll-feed
  - jekyll-include-cache

# Configuración del autor
author:
  name: Reewos Erwin Talla Chumpitaz
  bio: Científico de Datos | Apasionado por la Inteligencia Artificial
  location: Lima - Perú
  email: reewos.talla.c@uni.pe
  # twitter_username: tu_twitter
  github_username: reewos

# Enlaces sociales
social_links:
  # twitter: https://twitter.com/tu_usuario
  github: https://github.com/reewos

# Configuración de navegación
nav_links:
  - title: Proyectos
    url: /proyectos/
  - title: Habilidades
    url: /habilidades/
  - title: Acerca de mí
    url: /acerca-de/
  - title: Contacto
    url: /contacto/

# Opciones de permalinks (URLs permanentes)
permalink: /:title/
