# Configuración del sitio
title: Mi Portafolio de Data Science
description: Bienvenido a mi portafolio de Data Science. Aquí encontrarás información sobre mis proyectos, habilidades y experiencia en el campo de la ciencia de datos.
url: https://tu-usuario.github.io     # URL de tu sitio
baseurl: ""                           # Ruta base del sitio (dejar en blanco para GitHub Pages)

# Configuración de GitHub Pages
theme: jekyll-theme-minimal           # Tema predeterminado (puedes cambiarlo por el nombre de tu tema personalizado)
markdown: kramdown
plugins:
  - jekyll-feed

# Configuración del autor
author:
  name: Tu Nombre
  bio: Científico de Datos | Apasionado por la Inteligencia Artificial
  location: Tu ubicación
  email: tu@email.com
  twitter_username: tu_twitter
  github_username: tu_github

# Enlaces sociales
social_links:
  twitter: https://twitter.com/tu_usuario
  github: https://github.com/tu_usuario

# Configuración de navegación
nav_links:
  - title: Proyectos
    url: /proyectos/
  - title: Habilidades
    url: /habilidades/
  - title: Acerca de mí
    url: /acerca-de/
  - title: Contacto
    url: /contacto/

# Opciones de permalinks (URLs permanentes)
permalink: /:title/
